dataset_class: feedback_dataset
model_class: feedback_model
architecture:
    add_wide_dropout: true
    backbone: microsoft/deberta-large
    dropout: 0.1
    gradient_checkpointing: true
    pretrained_weights: ''
augmentation: {}
dataset:
    num_classes: 3
    fold: -1
    label_columns: tokens
    text_column: essay_text
    train_dataframe: data/pseudo_75_ff.pq
environment:
    mixed_precision: true
    number_of_workers: 4
    seed: -1
experiment_name: pseudo-75-ff
tokenizer:
    lowercase: false
    max_length: 2048
training:
    add_types: false
    batch_size: 4
    differential_learning_rate: 1.0e-05
    differential_learning_rate_layers: []
    drop_last_batch: true
    epochs: 1
    grad_accumulation: 1
    gradient_clip: 5
    is_pseudo: true
    learning_rate: 2.0e-05
    loss_function: CrossEntropy
    optimizer: AdamW
    schedule: Linear
    train_validation_data: true
    warmup_epochs: 0.5
    weight_decay: 0.001
