dataset_class: feedback_dataset
model_class: feedback_model
architecture:
    add_wide_dropout: true
    backbone: microsoft/deberta-large
    dropout: 0.1
    gradient_checkpointing: true
    pretrained_weights: output/pseudo-140-ff/checkpoint.pth
dataset:
    fold: -1
    label_columns: tokens
    num_classes: 3
    text_column: essay_text
    train_dataframe: data/feedback_text_token_classification_types.pq
environment:
    mixed_precision: true
    number_of_workers: 4
    seed: -1
experiment_name: conscious-uakari-ff
tokenizer:
    lowercase: false
    max_length: 2048
training:
    add_types: true
    batch_size: 4
    differential_learning_rate: 1.0e-05
    differential_learning_rate_layers: []
    drop_last_batch: true
    epochs: 2
    grad_accumulation: 1
    gradient_clip: 5
    is_pseudo: false
    learning_rate: 2.0e-05
    loss_function: CrossEntropy
    optimizer: AdamW
    schedule: Linear
    train_validation_data: true
    warmup_epochs: 1
    weight_decay: 0.001
