dataset_class: feedback_essay_ds
model_class: feedback_essay_model
architecture:
    aux_type: false
    backbone: microsoft/deberta-v3-large
    custom_intermediate_dropout: true
    dropout: 0
    gradient_checkpointing: false
    intermediate_dropout: 0
    pool: All [CLS] token
    pretrained_weights: ''
    use_sep: false
    use_type: true
    wide_dropout: 0
dataset:
    add_group_types: true
    fold: -1
    group_discourse: true
    label_columns:
    - discourse_effectiveness_Adequate
    - discourse_effectiveness_Effective
    - discourse_effectiveness_Ineffective
    separator: ''
    text_column:
    - essay_text
    train_dataframe: data/pseudoold_oof_164_fold_ff.csv
environment:
    mixed_precision: true
    number_of_workers: 4
    seed: -1
experiment_name: efficiency_model
tokenizer:
    add_newline_token: true
    lowercase: false
    max_length: 2048
training:
    aux_loss_function: CrossEntropy
    batch_size: 1
    differential_learning_rate: 1.0e-05
    differential_learning_rate_layers: []
    drop_last_batch: true
    epoch_subsample: 0
    epochs: 4
    grad_accumulation: 6
    gradient_clip: 0
    learning_rate: 7.0e-06
    loss_function: CrossEntropy
    mask_probability: 0
    mixup_concentration: 1
    mixup_probability: 0
    optimizer: AdamW
    schedule: Linear
    train_validation_data: true
    warmup_epochs: 0
    weight_decay: 0
