dataset_class: feedback_dataset
model_class: feedback_model
architecture:
    backbone: microsoft/deberta-large
    dropout: 0.1
    gradient_checkpointing: true
    pretrained_weights: ''
dataset:
    num_classes: 3
    fold: -1
    label_columns: tokens
    text_column: essay_text
    train_dataframe: data/feedback_text_token_classification_v5.pq
environment:
    mixed_precision: true
    number_of_workers: 4
    seed: -1
experiment_name: olivine-spaniel-ff
tokenizer:
    lowercase: false
    max_length: 2048
training:
    is_pseudo: false
    batch_size: 4
    differential_learning_rate: 1.0e-05
    differential_learning_rate_layers: []
    drop_last_batch: true
    epochs: 2
    grad_accumulation: 1
    gradient_clip: 1
    learning_rate: 3.0e-05
    loss_function: CrossEntropy
    optimizer: AdamW
    schedule: Linear
    train_validation_data: true
    warmup_epochs: 1
    weight_decay: 0.01
